-- require("plugins.catppuccin")
require("plugins.lualine")
require("plugins.treesitter")
require("plugins.nvim-tree-lua")
require("plugins.telescope-nvim")
require("plugins.nvim-cmp")
require("plugins.nvim-lspconfig")
require("plugins.which-key-lua")
require("plugins.noice")
require("plugins.lazygit-nvim")
require("plugins.nvim-comments")
require("plugins.alpha-nvim")
require("plugins.indent-blankline-nvim")
