require("plugins.catppuccin")
require("plugins.lualine")
require("plugins.treesitter")
require("plugins.nvim-tree-lua")
require("plugins.telescope-nvim")
require("plugins.nvim-cmp")
require("plugins.nvim-lspconfig")
require("plugins.which-key-lua")
